using System;
using System.Collections.Generic;
using System.Windows.Forms;
using EscPOSThermalPrinter.model;
using Newtonsoft.Json;
using WebSocketSharp;
using WebSocketSharp.Server;
using ESCPOS_NET;
using ESC_POS_USB_NET.Printer;
using ESC_POS_USB_NET.Enums;
using System.Drawing;
using System.IO;
using System.IO.Ports;
using ESCPOS_NET.Emitters;
using ESCPOS_NET.Utilities;
using InTheHand.Net.Bluetooth;
using InTheHand.Net.Sockets;
using InTheHand.Net;

namespace PrinterApp {

public static class GlobalStaticVariablesMaintain
    {
        public static bool IsOpen { get; set; }
    }

    public class AccessListOfBluetoothPrinters : WebSocketBehavior
    {

        //https://github.com/inthehand/32feet/wiki
        //https://inthehand.github.io/html/T_InTheHand_Net_Sockets_BluetoothDeviceInfo.htm
        protected override void OnMessage(MessageEventArgs e)
        {
            BluetoothClient localClient = new BluetoothClient();
            BluetoothDeviceInfo[] deviceList = localClient.DiscoverDevices(255, false, true, false, false);
            if (deviceList.Length > 0) { 

                


            foreach (BluetoothDeviceInfo device in deviceList)
                {
                    if (SerialPort.GetPortNames().Length > 0)
                    {
                        foreach (string comPort in SerialPort.GetPortNames())
                        {
                            Send("deviceName=" + device.DeviceName.ToString() + "#comPort="+comPort + "#deviceAddress=" + device.DeviceAddress.ToString());
                        }
                    }
                   
                }
            }

        }
    }

    //end point 1
    public class AccessListOfPrinters : WebSocketBehavior
{
        
        protected override void OnMessage(MessageEventArgs e)
    {
        if (System.Drawing.Printing.PrinterSettings.InstalledPrinters.Count > 0)
        {
            foreach (string printer in System.Drawing.Printing.PrinterSettings.InstalledPrinters) { Send(printer); }
        }
    }
}

    //end point 2
    public class POSMSGES : WebSocketBehavior
    {
        public string yourPrinterName = "POS80(2)";
        public string space = "\x20";//hex unicode for add space in the string
        public string base64Image = "Qk26nAAAAAAAAHoAAABsAAAAZAAAAGQAAAABACAAAwAAAECcAADEDgAAxA4AAAAAAAAAAAAAAAD/AAD/AAD/AAAAAAAA/yBuaVcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////g4OD/tLS0/5SUlP96enr/XFxc/z8/P/8vLy//JSUl/xUVFf8VFRX/AAAA/wAAAP8NDQ3/FRUV/x0dHf8qKir/PT09/1FRUf9vb2//ioqK/6enp//S0tL//Pz8///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////r6+v/n5+f/1tbW/8bGxv/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wcHB/8/Pz//h4eH/8/Pz////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////7u7u/9PT0//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/Ly8v/5ubm//v7+/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////s7Oz/f39//xsbG/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/BwcH/1dXV//U1NT/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////9PT0/7S0tP9fX1//Dw8P/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AwMD/0JCQv+SkpL/39/f////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////r6+v/xMTE/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP98fHz/+/v7///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////n5+f/X19f/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/ysrK/+7u7v///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////+Tk5P/Dw8P/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/1dXV//n5+f//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////7a2tv8lJSX/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/CgoK/4iIiP/8/Pz/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////+/v7/3d3d/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/MzMz/9/f3///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////5+fn/z8/P/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8PDw//t7e3////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////39/f/xsbG/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wMDA/+vr6//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////8/Pz/zQ0NP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/Dw8P/8fHx///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////wcHB/ycnJ/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8HBwf/hISE//f39///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////j4+P/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP87Ozv/9/f3////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////x8fH/wMDA/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/4SEhP//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////+/v7/ycnJ/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8HBwf/x8fH////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////5OTk/zo6Ov8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/w8PD/+vr6//////////////////////////////////////////////////////////////////////////////////////////////////////////////////8/Pz/ycnJ/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AwMD/7e3t////////////////////////////////////////////////////////////////////////////////////////////////////////////09PT/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8iIiL/XFxc/2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/zg4OP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8PDw//39/f/////////////////////////////////////////////////////////////////////////////////////////////////5OTk/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/ywsLP+zs7P//Pz8////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////39/f/2dnZ/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/zMzM//8/Pz//////////////////////////////////////////////////////////////////////////////////////8jIyP8FBQX/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/EBAQ/5qamv/8/Pz/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////0tLS/zg4OP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/iIiI//////////////////////////////////////////////////////////////////////////////////////88PDz/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/7u7u//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////z8/P/Ghoa/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/woKCv/n5+f///////////////////////////////////////////////////////////////////////////+3t7f/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/zU1Nf//////////////////////ra2t/ywsLP8gICD/ICAg/yAgIP8gICD/ICAg/yAgIP8gICD/ICAg/yAgIP8gICD/ICAg/yAgIP8gICD/ICAg/yAgIP8gICD/ICAg/yAgIP8gICD/ICAg/yAgIP8gICD/ICAg/yAgIP8gICD/ICAg/yAgIP8gICD/ICAg/yAgIP8gICD/ICAg/yAgIP8gICD/ICAg/yAgIP8gICD/ICAg/yAgIP8gICD/ICAg/yAgIP8gICD/ICAg/yAgIP99fX3//////////////////////3V1df8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/V1dX///////////////////////////////////////////////////////////////////////7+/v/IyMj/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP93d3f/////////////////x8fH/wgICP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/3Nzc/////////////////+8vLz/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP+7u7v/////////////////////////////////////////////////////////////////i4uL/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/oqKi/////////////////zQ0NP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/09PT////////////4uLi/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/Kysr//v7+///////////////////////////////////////////////////////1NTU/woKCv8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/7q6uv///////////+rq6v8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/4eHh/////////////v7+/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP98fHz//////////////////////////////////////////////////////z8/P/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP+/v7/////////////f39//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP9/f3//////////////////AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/9/f3////////////////////////////////////////////9TU1P8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/v7+/////////////39/f/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/f39//////////////////wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP+SkpL///////////////////////////////////////////+EhIT/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/7+/v////////////9/f3/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/xAQEP97e3v/vLy8/4eHh/8UFBT/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/39/f/////////////////8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/QkJC////////////////////////////////////////////KCgo/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP+/v7/////////////f39//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/EBAQ/39/f/9/f3//f39//39/f/9/f3//f39//39/f/9/f3//f39//39/f/9/f3//f39//39/f/9/f3//f39//39/f/9/f3//f39//yAgIP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/zAwMP/k5OT/////////////////7+/v/z09Pf8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP9/f3//////////////////AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wMDA//U1NT/////////////////////////////////t7e3/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/v7+/////////////39/f/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/yAgIP////////////////////////////////////////////////////////////////////////////////////////////////9AQED/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP+np6f///////////////////////////+3t7f/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/f39//////////////////wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/V1dX/////////////////////////////////1tbW/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/7+/v////////////9/f3/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8gICD/////////////////////////////////////////////////////////////////////////////////////////////////QEBA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/v7+/////////////////////////////09PT/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/39/f/////////////////8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wcHB//v7+////////////////////////Pz8/8HBwf/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP+/v7/////////////f39//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/ICAg/////////////////////////////////////////////////////////////////////////////////////////////////0BAQP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/4eHh////////////////////////////5+fn/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP9/f3//////////////////AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/m5ub//////////////////////+RkZH/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/v7+/////////////39/f/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wUFBf8qKir/Kioq/yoqKv8qKir/Kioq/yoqKv8qKir/Kioq/yoqKv8qKir/Kioq/yoqKv8qKir/Kioq/yoqKv8qKir/Kioq/yoqKv8KCgr/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8NDQ3/rKys//z8/P///////////6+vr/8VFRX/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/f39//////////////////wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/y8vL///////////////////////MzMz/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/7+/v////////////9/f3/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8cHBz/UlJS/yQkJP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/39/f/////////////////8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/z8/P////////////5+fn/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP+/v7/////////////f39//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP9/f3//////////////////AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/4eHh////////////6enp/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/v7+/////////////39/f/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/f39//////////////////wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8/Pz////////////9nZ2f/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/7+/v////////////9/f3/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/39/f/////////////////8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/BwcH//z8/P//////Hx8f/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP+/v7/////////////f39//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP9/f3//////////////////AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP/S0tL/39/f/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/v7+/////////////39/f/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/f39//////////////////wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/p6en/7Ozs/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/7+/v////////////9/f3/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/39/f/////////////////8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/4qKiv+Li4v/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP+/v7/////////////f39//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP9/f3//////////////////AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP9vb2//X19f/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/v7+/////////////39/f/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/f39//////////////////wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/UVFR/zs7O/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/7+/v////////////9/f3/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/39/f/////////////////8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/z09Pf8fHx//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP+/v7/////////////f39//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP9/f3//////////////////AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8qKir/Dw8P/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/v7+/////////////39/f/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/f39//////////////////wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/HR0d/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/7+/v////////////9/f3/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/39/f/////////////////8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/xUVFf8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP+/v7/////////////f39//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP9/f3//////////////////AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8NDQ3/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/v7+/////////////39/f/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/f39//////////////////wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/7+/v////////////9/f3/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/39/f/////////////////8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wICAv8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP+/v7/////////////f39//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP9/f3//////////////////AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8VFRX/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/v7+/////////////39/f/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/woKCv9VVVX/VVVV/1VVVf9VVVX/VVVV/1VVVf9VVVX/VVVV/1VVVf9VVVX/VVVV/1VVVf9VVVX/VVVV/1VVVf9VVVX/VVVV/1VVVf9VVVX/VVVV/1VVVf9VVVX/VVVV/1VVVf9VVVX/VVVV/1VVVf9VVVX/VVVV/1VVVf9VVVX/VVVV/1VVVf9VVVX/VVVV/1VVVf81NTX/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/f39//////////////////wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/FRUV/xsbG/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/7+/v////////////9/f3/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8gICD/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////n5+f/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/39/f/////////////////8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/yUlJf8nJyf/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP+/v7/////////////f39//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/ICAg/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////5+fn/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP9/f3//////////////////AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8vLy//Q0ND/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/v7+/////////////39/f/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/yAgIP////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////+fn5//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/f39//////////////////wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/Pz8//2xsbP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/6+vr/////////////f39/8NDQ3/AAAA/wAAAP8AAAD/AAAA/wAAAP8KCgr/VVVV/5WVlf////////////////9qamr/VVVV/1VVVf9VVVX/VVVV/1VVVf9VVVX/VVVV/1VVVf9VVVX/VVVV/1VVVf9VVVX/VVVV/1VVVf9VVVX/VVVV/1VVVf9VVVX/VVVV/1VVVf9VVVX/VVVV/1VVVf9VVVX/VVVV/9TU1P///////////9TU1P9VVVX/NTU1/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/6Kiov////////////Ly8v8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/1xcXP+Xl5f/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP+Kior/////////////////h4eH/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP9gYGD/////////////////ICAg/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP+/v7////////////+/v7//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/ywsLP/7+/v////////////MzMz/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP96enr/x8fH/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/T09P//////////////////////9XV1f/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/YGBg/////////////////yAgIP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/v7+/////////////v7+//wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/yUlJf/n5+f/////////////////kpKS/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/lJSU/+/v7/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/woKCv/r6+v//////////////////////8/Pz/+/v7//v7+//7+/v/+/v7//v7+//9fX1/////////////////8gICD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/7+/v////////////+/v7/+/v7//v7+//7+/v/+/v7//v7+//8PDw//39/f//////////////////////z09Pf8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/7S0tP//////NDQ0/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/MDAw/9fX1///////////////////////////////////////////////////////////////////////ICAg/wAAAP8AAAD/AAAA/zAwMP9AQED/QEBA/ygoKP8AAAD/AAAA/yUlJf9AQED/QEBA/0BAQP9AQED/QEBA/0BAQP9AQED/QEBA/0BAQP9AQED/EBAQ/wAAAP8AAAD/AAAA/wAAAP+/v7//////////////////////////////////////////////////////////////////9/f3/29vb/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP/g4OD//////39/f/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8EBAT/h4eH//f39////////////////////////////////////////////////////////////yAgIP8AAAD/AAAA/wAAAP+/v7////////////+fn5//AAAA/wAAAP+VlZX//////////////////////////////////////////////////////0BAQP8AAAD/AAAA/wAAAP8AAAD/v7+/////////////////////////////////////////////////////////////w8PD/yQkJP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8bGxv///////////+/v7//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8YGBj/fX19/7u7u/+/v7//v7+//7+/v/+/v7//v7+//9fX1/////////////////8gICD/AAAA/wAAAP8AAAD/v7+/////////////n5+f/wAAAP8AAAD/lZWV//////////////////////////////////////////////////////9AQED/AAAA/wAAAP8AAAD/AAAA/7+/v////////////+/v7/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+VlZX/ODg4/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/W1tb////////////9/f3/wsLC/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP9gYGD/////////////////ICAg/wAAAP8AAAD/AAAA/7+/v////////////5+fn/8AAAD/AAAA/5WVlf//////////////////////////////////////////////////////QEBA/wAAAP8AAAD/AAAA/wAAAP+/v7////////////+/v7//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/5+fn/////////////////9PT0//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/YGBg/////////////////yAgIP8AAAD/AAAA/wAAAP93d3f/n5+f/5+fn/9jY2P/AAAA/wAAAP9dXV3/n5+f/5+fn/+fn5//n5+f/5+fn/+fn5//n5+f/5+fn/+fn5//n5+f/ygoKP8AAAD/AAAA/wAAAP8AAAD/v7+/////////////v7+//wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP/r6+v/////////////////r6+v/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/2BgYP////////////////8gICD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/7+/v////////////7+/v/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP9PT0////////////////////////////8fHx//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP9gYGD/////////////////ICAg/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP+/v7////////////+/v7//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/u7u7////////////////////////////f39//wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/YGBg/////////////////yAgIP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/v7+/////////////v7+//wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/Gxsb/////////////////////////////////9/f3/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/2BgYP////////////////8gICD/AAAA/wAAAP8AAAD/p6en/9/f3//f39//i4uL/wAAAP8AAAD/goKC/9/f3//f39//39/f/9/f3//f39//39/f/9/f3//f39//39/f/9/f3/84ODj/AAAA/wAAAP8AAAD/AAAA/7+/v////////////7+/v/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/39/f///////////////////////////////////////RERE/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP9gYGD/////////////////ICAg/wAAAP8AAAD/AAAA/7+/v////////////5+fn/8AAAD/AAAA/5WVlf//////////////////////////////////////////////////////QEBA/wAAAP8AAAD/AAAA/wAAAP+/v7///////////////////////////////////////2BgYP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/w8PD//s7Oz//////////////////////////////////////5+fn/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/YGBg/////////////////yAgIP8AAAD/AAAA/wAAAP+/v7////////////+fn5//AAAA/wAAAP+VlZX//////////////////////////////////////////////////////0BAQP8AAAD/AAAA/wAAAP8AAAD/v7+///////////////////////////////////////9vb2//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP9fX1/////////////////////////////////////////////v7+//BwcH/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/2BgYP////////////////8gICD/AAAA/wAAAP8AAAD/d3d3/5+fn/+fn5//Y2Nj/wAAAP8AAAD/XV1d/5+fn/+fn5//n5+f/5+fn/+fn5//n5+f/5+fn/+fn5//n5+f/5+fn/8oKCj/AAAA/wAAAP8AAAD/AAAA/7+/v///////////////////////////////////////d3d3/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/tLS0/////////////////////////////////////////////////29vb/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP9gYGD/////////////////ICAg/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP+/v7/////////////f39//j4+P/////////////////2BgYP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/FxcX//T09P/////////////////////////////////////////////////v7+//IiIi/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/YGBg/////////////////yAgIP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/v7+/////////////v7+//1hYWP////////////////89PT3/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/6+vr////////////////////////////////////////////////////////////8PDw/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/2BgYP////////////////8gICD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/7+/v////////////7+/v/+zs7P////////////39/f/CAgI/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/19fX///////////////////////////////////////////////////////////////////////V1dX/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP9gYGD/////////////////ODg4/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP+/v7/////////////r6+v/////////////////r6+v/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/w8PD//n5+f//////////////////////////////////////////////////////////////////////+fn5/8KCgr/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/ODg4/////////////////+vr6/+Li4v/f39//39/f/9/f3//f39//39/f/9/f3//f39//39/f/9/f3//f39//39/f/9/f3//f39//39/f/9/f3//f39//39/f/9/f3//f39//39/f/9/f3//f39//39/f/9/f3//39/f/////////////////////////////////1BQUP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP+Tk5P/////////////////////////////////////////////////////////////////////////////////ampq/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP/f39///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////9TU1P8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8lJSX//////////////////////////////////////////////////////////////////////////////////////+bm5v8dHR3/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/TExM//Hx8f///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////+Li4v83Nzf/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/tra2////////////////////////////////////////////////////////////////////////////////////////////z8/P/wcHB/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8UFBT/i4uL/9PT0//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////5+fn/x8fH/29vb/8ICAj/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/d3d3//////////////////////////////////////////////////////////////////////////////////////////////////////+fn5//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/Pz8///v7+////////////////////////////////////////////////////////////////////////////////////////////////////////////2dnZ/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/Gxsb/+fn5//////////////////////////////////////////////////////////////////////////////////////////////////////////////////8/Pz/eXl5/wEBAf8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/NDQ0/9/f3/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////9fX1//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/Jycn//Pz8///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////7+/v/ycnJ/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/8HBwf/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////b29v/Jycn/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AwMD/4+Pj////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////+/v7/9fX1//AQEB/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/Jycn/8fHx////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////3l5ef8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/Ojo6//v7+//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////8/Pz/Z2dn/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/Jycn/+Tk5P////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////+fn5//BwcH/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/T09P//Pz8////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////8/Pz/8dHR3/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8FBQX/k5OT////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////5ubm/2pqav8KCgr/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP88PDz/yMjI////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////5+fn/1tbW/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/yMjI/+3t7f/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////w8PD/yIiIv8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/CgoK/4uLi//7+/v////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////v7+//b29v/wcHB/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/Pz8//9TU1P/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////v7+//n5+f/0RERP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/ygoKP+EhIT/1NTU////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////39/f/39/f/8jIyP/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8HBwf/W1tb/7e3t////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////6+vr/9PT0//CwsL/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/zMzM/+RkZH/8/Pz//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////f39/+/v7//f39//zc3N/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/x8fH/9nZ2f/p6en/+fn5///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////8/Pz/8fHx/+Xl5f/bGxs/0NDQ/8rKyv/Gxsb/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/w8PD/8fHx//Ozs7/19fX/+Li4v/s7Oz/9/f3///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////";
        SerialPrinter printerEpsonBluetooth = null;
        //var printerEpsonBluetooth = new SerialPrinter(portName: "COM6", baudRate: 115200);

        public Bitmap base64ImageToBitmap(string base64String)
        {
            Bitmap bmpReturn = null;
            byte[] byteBuffer = Convert.FromBase64String(base64String);
            MemoryStream memoryStream = new MemoryStream(byteBuffer);
            memoryStream.Position = 0;
            bmpReturn = (Bitmap)Bitmap.FromStream(memoryStream);
            memoryStream.Close();
            memoryStream = null;
            byteBuffer = null;
            return bmpReturn;
        }
        public string stringEndToAddSpace(String n, int l)
        {
            string nm = "";
            nm = n;
            for (int i = 0; i < (l - n.Length); i++)
            {
                nm = nm + space;
            }
            return nm;
        }
        public string stringFrontToAddSpace(String n, int l)
        {
            string nm = "";
            for (int i = 0; i < l; i++)
            {
                nm = nm + space;
            }
            return nm + n;
        }

        private void printByBluetooth(RecieptJsonClass recieptJsonClass)
        {
            ByteArrayBuilder byteArrayBuilderForBlueooth = new ByteArrayBuilder();
            
            if(GlobalStaticVariablesMaintain.IsOpen == false){
                GlobalStaticVariablesMaintain.IsOpen = true;
                List<String> bluetoothGet = new List<String>(recieptJsonClass.printerName.ToString().Split("=".ToCharArray()));
                printerEpsonBluetooth = new SerialPrinter(portName: bluetoothGet[1], baudRate: 115200);
            }

            var ep = new EPSON();

            if (!recieptJsonClass.openDrawer.ToString().IsNullOrEmpty() && recieptJsonClass.openDrawer)
            {
                byteArrayBuilderForBlueooth.Append(ep.CashDrawerOpenPin2(120, 240));
            }

            if (!recieptJsonClass.topLogoBase64String.ToString().IsNullOrEmpty())
            { }


            int i = 1;
            if (recieptJsonClass.content.Count > 0)
            {
                foreach (var item in recieptJsonClass.content)
                {
                    Content contentObject = JsonConvert.DeserializeObject<Content>(item.ToString());

                    Boolean v = contentObject.value.ToString().IsNullOrEmpty();
                    Boolean b = contentObject.bold.ToString().IsNullOrEmpty();
                    Boolean u = contentObject.underline.ToString().IsNullOrEmpty();
                    Boolean f = contentObject.fontType.ToString().IsNullOrEmpty();
                    Boolean w = contentObject.size.ToString().IsNullOrEmpty();
                    Boolean br = contentObject.barcode.ToString().IsNullOrEmpty();
                    Boolean qr = contentObject.qrcode.ToString().IsNullOrEmpty();
                    Boolean ac = recieptJsonClass.autoCut.ToString().IsNullOrEmpty();

                    if (!contentObject.align.ToString().IsNullOrEmpty())
                    {
                        if (contentObject.align == "left" || contentObject.align == "right" || contentObject.align == "center")
                        {

                            if (contentObject.align == "left")
                            {
                                byteArrayBuilderForBlueooth.Append(ep.LeftAlign());
                            }
                            else if (contentObject.align == "right")
                            {
                                byteArrayBuilderForBlueooth.Append(ep.RightAlign());

                            }
                            else if (contentObject.align == "center")
                            {
                                byteArrayBuilderForBlueooth.Append(ep.CenterAlign());
                            }
                            else
                            {
                                byteArrayBuilderForBlueooth.Append(ep.LeftAlign());
                            }
                        }
                    }
                    else
                    {
                        byteArrayBuilderForBlueooth.Append(ep.LeftAlign());
                    }

                    if (!w && contentObject.size.ToString().Equals("1"))
                    {
                        byteArrayBuilderForBlueooth.Append(ep.SetStyles(PrintStyle.DoubleWidth));
                        byteArrayBuilderForBlueooth.Append(ep.SetStyles(PrintStyle.DoubleHeight));

                        //printer.NormalWidth();
                    }
                    else if (!w && contentObject.size.ToString().Equals("2"))
                    {
                        byteArrayBuilderForBlueooth.Append(ep.SetStyles(PrintStyle.DoubleWidth));
                        byteArrayBuilderForBlueooth.Append(ep.SetStyles(PrintStyle.DoubleHeight));
                        //printer.DoubleWidth2();
                    }
                    else if (!w && contentObject.size.ToString().Equals("3"))
                    {
                        byteArrayBuilderForBlueooth.Append(ep.Print("\x1b\x45\x01"));
                        //byteArrayBuilder.Append(e.SetStyles(PrintStyle.DoubleWidth));
                        //byteArrayBuilder.Append(e.SetStyles(PrintStyle.DoubleHeight));
                        //printer.DoubleWidth3();
                    }
                    else
                    {
                        byteArrayBuilderForBlueooth.Append(ep.SetStyles(PrintStyle.None));
                        //printer.NormalWidth();
                    }


                    if (!(b) && !(u) && contentObject.bold && contentObject.underline)
                    {

                        byteArrayBuilderForBlueooth.Append(ep.SetStyles(PrintStyle.Bold));
                        byteArrayBuilderForBlueooth.Append(ep.SetStyles(PrintStyle.Underline));
                    }
                    else if (!(b) && !(u) && contentObject.bold && !(contentObject.underline))
                    {
                        byteArrayBuilderForBlueooth.Append(ep.SetStyles(PrintStyle.Bold));
                    }
                    else if (!(b) && !(u) && contentObject.underline && !(contentObject.bold))
                    {
                        byteArrayBuilderForBlueooth.Append(ep.SetStyles(PrintStyle.Underline));
                    }
                    else
                    {
                        byteArrayBuilderForBlueooth.Append(ep.SetStyles(PrintStyle.None));
                    }


                    if (!(br) && v)
                    {
                        byteArrayBuilderForBlueooth.Append(ep.SetBarcodeHeightInDots(300));
                        byteArrayBuilderForBlueooth.Append(ep.SetBarWidth(BarWidth.Thin));
                        byteArrayBuilderForBlueooth.Append(ep.SetBarLabelPosition(BarLabelPrintPosition.None));
                        byteArrayBuilderForBlueooth.Append(ep.PrintBarcode(BarcodeType.CODE128, contentObject.barcode.ToString()));
                        byteArrayBuilderForBlueooth.Append(ep.PrintLine(""));
                    }

                    if (!(qr) && v && !(w))
                    {
                        if (contentObject.size.ToString().Equals("1"))
                        {
                            byteArrayBuilderForBlueooth.Append(ep.PrintQRCode(contentObject.qrcode.ToString(), TwoDimensionCodeType.QRCODE_MODEL2, Size2DCode.NORMAL, CorrectionLevel2DCode.PERCENT_7));
                            byteArrayBuilderForBlueooth.Append(ep.PrintLine(""));

                        }
                        else if (contentObject.size.ToString().Equals("2"))
                        {
                            byteArrayBuilderForBlueooth.Append(ep.PrintQRCode(contentObject.qrcode.ToString(), TwoDimensionCodeType.QRCODE_MODEL2, Size2DCode.LARGE, CorrectionLevel2DCode.PERCENT_7));
                            byteArrayBuilderForBlueooth.Append(ep.PrintLine(""));

                        }
                        else if (contentObject.size.ToString().Equals("0"))
                        {
                            byteArrayBuilderForBlueooth.Append(ep.PrintQRCode(contentObject.qrcode.ToString(), TwoDimensionCodeType.QRCODE_MODEL2, Size2DCode.SMALL, CorrectionLevel2DCode.PERCENT_7));
                            byteArrayBuilderForBlueooth.Append(ep.PrintLine(""));

                        }
                        else
                        {
                            byteArrayBuilderForBlueooth.Append(ep.PrintQRCode(contentObject.qrcode.ToString(), TwoDimensionCodeType.QRCODE_MODEL2, Size2DCode.LARGE, CorrectionLevel2DCode.PERCENT_7));
                            byteArrayBuilderForBlueooth.Append(ep.PrintLine(""));

                        }

                    }

                    if (!contentObject.logoBase64String.ToString().IsNullOrEmpty() && v)
                    {
                        //Bitmap codeBitmap = new Bitmap(base64ImageToBitmap(contentObject.logoBase64String.ToString()));
                        //Image image = (Image)codeBitmap;
                        //ImageConverter converter = new ImageConverter();
                        //byteArrayBuilder.Append(e.PrintImage((byte[])converter.ConvertTo(image, typeof(byte[])), true));
                        //e.PrintImage(File.ReadAllBytes("images/pd-logo-300.png"), true),
                        //printer.Image(image);

                    }

                    if (!(v) && !(f) && contentObject.fontType.ToString().Equals("A"))
                    {
                        //https://escpos.readthedocs.io/en/latest/font_cmds.html
                        byteArrayBuilderForBlueooth.Append(ep.Print("\x1b\x50\x01"));
                        byteArrayBuilderForBlueooth.Append(ep.PrintLine(contentObject.value.ToString()));
                    }
                    if (!(v) && !(f) && !f && contentObject.fontType.ToString().Equals("B"))
                    {
                        byteArrayBuilderForBlueooth.Append(ep.SetStyles(PrintStyle.FontB));
                        byteArrayBuilderForBlueooth.Append(ep.Print("\x1b\x50\x01"));
                        byteArrayBuilderForBlueooth.Append(ep.PrintLine(contentObject.value.ToString()));
                    }
                    if (!(v) && !(f) && contentObject.fontType.ToString().Equals("C"))
                    {
                        //byteArrayBuilder.Append(e.SetStyles(PrintStyle.FontB));
                        byteArrayBuilderForBlueooth.Append(ep.Print("\x1b\x54\x01"));
                        byteArrayBuilderForBlueooth.Append(ep.PrintLine(contentObject.value.ToString()));
                    }
                    if (!(v) && !(f) && contentObject.fontType.ToString().Equals("D"))
                    {
                        byteArrayBuilderForBlueooth.Append(ep.SetStyles(PrintStyle.FontB));
                        byteArrayBuilderForBlueooth.Append(ep.Print("\x1b\x55\x01"));
                        byteArrayBuilderForBlueooth.Append(ep.PrintLine(contentObject.value.ToString()));
                    }
                    if (!(v) && !(f) && contentObject.fontType.ToString().Equals("E"))
                    {
                        byteArrayBuilderForBlueooth.Append(ep.Print("\x1b\x55\x01"));
                        byteArrayBuilderForBlueooth.Append(ep.PrintLine(contentObject.value.ToString()));
                    }

                    if (!contentObject.newLines.ToString().IsNullOrEmpty() && contentObject.newLines > 1)
                    {
                        for (int x = 0; x < contentObject.newLines - 1; x++)
                        {
                            byteArrayBuilderForBlueooth.Append(ep.PrintLine(""));
                        }

                    }

                    if (!contentObject.separator.ToString().IsNullOrEmpty())
                    {
                        byteArrayBuilderForBlueooth.Append(ep.SetStyles(PrintStyle.None));
                        byteArrayBuilderForBlueooth.Append(ep.CenterAlign());
                        //this one for 80mm paper role
                        string sep = "------------------------------------------------";
                        string newSep = "";
                        foreach (char ch in sep)
                        {
                            newSep = newSep + (contentObject.separator.ToString().ToCharArray()[0]);
                        }
                        byteArrayBuilderForBlueooth.Append(ep.PrintLine(newSep));

                    }
                    byteArrayBuilderForBlueooth.Append(ep.SetStyles(PrintStyle.None));

                    i++;
                }
                i = 1;
            }

            byteArrayBuilderForBlueooth.Append(ep.LeftAlign());
            byteArrayBuilderForBlueooth.Append(ep.PrintLine(""));
            byteArrayBuilderForBlueooth.Append(ep.PrintLine(""));
            byteArrayBuilderForBlueooth.Append(ep.PrintLine(""));
            byteArrayBuilderForBlueooth.Append(ep.PrintLine(""));

            if (!recieptJsonClass.autoCut.ToString().IsNullOrEmpty() && recieptJsonClass.autoCut)
            {
                byteArrayBuilderForBlueooth.Append(ep.FullCut());
            }


            try
            {
                printerEpsonBluetooth.Write(byteArrayBuilderForBlueooth.ToArray());
            }
            catch (Exception ex)
            {
                throw ex;
            }

            byteArrayBuilderForBlueooth.Clear();

        }

        private void printByIPAddress(RecieptJsonClass recieptJsonClass)
        {
            //https://github.com/lukevp/ESC-POS-.NET
            ByteArrayBuilder byteArrayBuilder = new ByteArrayBuilder();
            List<String> ipGet = new List<String>(recieptJsonClass.printerName.ToString().Split("=".ToCharArray()));
            
            // Ethernet or WiFi (This uses an Immediate Printer, no live paper status events, but is easier to use)
            var hostnameOrIp = ipGet[1];//"192.168.8.200";
            var port = 0;
            //var printerEpson = new ImmediateNetworkPrinter(new ImmediateNetworkPrinterSettings() { ConnectionString = $"{hostnameOrIp}:{port}", PrinterName ="Thermal Printer" });
            var printerEpson = new ImmediateNetworkPrinter(new ImmediateNetworkPrinterSettings() { ConnectionString = $"{hostnameOrIp}", PrinterName = "Thermal Printer" });

            //print using USB, Bluetooth, or Serial
            //var printerEpson = new SerialPrinter(portName: "COM5", baudRate: 115200);

            //print using Linux output to USB / Serial file
            // var printerEpson = new FilePrinter(filePath: "/dev/usb/lp0");

            //print using Samba
            //var printer = new SambaPrinter(tempFileBasePath: @"C:\Temp", filePath: "\\computer\printer");

            //Style.FontB < Style.None

            var e = new EPSON();

            if (!recieptJsonClass.openDrawer.ToString().IsNullOrEmpty() && recieptJsonClass.openDrawer)
            {
                byteArrayBuilder.Append(e.CashDrawerOpenPin2(120, 240));
            }

            if (!recieptJsonClass.topLogoBase64String.ToString().IsNullOrEmpty())
                 {
                //string imagePath = @"C:\MY DATA FOLDER\Projects\newprinterc\PrinterApp\Icon.bmp";
                //Bitmap codeBitmap = new Bitmap(base64ImageToBitmap(recieptJsonClass.topLogoBase64String.ToString()));
                       
                //Bitmap codeBitmap2 = new Bitmap(Bitmap.FromFile(imagePath));

                //Image image = (Image)codeBitmap2;

                //ImageConverter converter = new ImageConverter();
                //byteArrayBuilder.Append(e.CenterAlign());
                        
                //byteArrayBuilder.Append(e.BufferImage((byte[])converter.ConvertTo(image, typeof(byte[]))));
                //byteArrayBuilder.Append(e.PrintImage(File.ReadAllBytes(imagePath), true));
                //byteArrayBuilder.Append(e.PrintImage((byte[])converter.ConvertTo(image, typeof(byte[])),true));
                //byteArrayBuilder.Append(e.PrintLine("\n\n\n"));
                //e.PrintImage(File.ReadAllBytes("images/pd-logo-300.png"), true),
                //printer.Image(image);
            }


                    int i = 1;
                if (recieptJsonClass.content.Count > 0)
                {
                    foreach (var item in recieptJsonClass.content)
                    {
                        Content contentObject = JsonConvert.DeserializeObject<Content>(item.ToString());

                        Boolean v = contentObject.value.ToString().IsNullOrEmpty();
                        Boolean b = contentObject.bold.ToString().IsNullOrEmpty();
                        Boolean u = contentObject.underline.ToString().IsNullOrEmpty();
                        Boolean f = contentObject.fontType.ToString().IsNullOrEmpty();
                        Boolean w = contentObject.size.ToString().IsNullOrEmpty();
                        Boolean br = contentObject.barcode.ToString().IsNullOrEmpty();
                        Boolean qr = contentObject.qrcode.ToString().IsNullOrEmpty();
                        Boolean ac = recieptJsonClass.autoCut.ToString().IsNullOrEmpty();



                        if (!contentObject.align.ToString().IsNullOrEmpty())
                        {
                            if (contentObject.align == "left" || contentObject.align == "right" || contentObject.align == "center")
                            {

                                if (contentObject.align == "left")
                                {
                                   byteArrayBuilder.Append(e.LeftAlign());
                                }
                                else if (contentObject.align == "right")
                                {
                                byteArrayBuilder.Append(e.RightAlign());

                                }
                                else if (contentObject.align == "center")
                                {
                                byteArrayBuilder.Append(e.CenterAlign());
                                }
                                else
                                {
                                byteArrayBuilder.Append(e.LeftAlign());
                                }
                            }
                        }
                        else
                        {
                        byteArrayBuilder.Append(e.LeftAlign());
                        }

                        if (!w && contentObject.size.ToString().Equals("1"))
                        {
                           byteArrayBuilder.Append(e.SetStyles(PrintStyle.DoubleWidth));
                           byteArrayBuilder.Append(e.SetStyles(PrintStyle.DoubleHeight));

                           //printer.NormalWidth();
                    }
                        else if (!w && contentObject.size.ToString().Equals("2"))
                        {
                        byteArrayBuilder.Append(e.SetStyles(PrintStyle.DoubleWidth));
                        byteArrayBuilder.Append(e.SetStyles(PrintStyle.DoubleHeight));
                        //printer.DoubleWidth2();
                    }
                        else if (!w && contentObject.size.ToString().Equals("3"))
                        {
                        byteArrayBuilder.Append(e.Print("\x1b\x45\x01"));
                        //byteArrayBuilder.Append(e.SetStyles(PrintStyle.DoubleWidth));
                        //byteArrayBuilder.Append(e.SetStyles(PrintStyle.DoubleHeight));
                        //printer.DoubleWidth3();
                    }
                        else
                        {
                        byteArrayBuilder.Append(e.SetStyles(PrintStyle.None));
                        //printer.NormalWidth();
                    }


                        if (!(b) && !(u) && contentObject.bold && contentObject.underline)
                        {

                        byteArrayBuilder.Append(e.SetStyles(PrintStyle.Bold));
                        byteArrayBuilder.Append(e.SetStyles(PrintStyle.Underline));
                        }
                        else if (!(b) && !(u) && contentObject.bold && !(contentObject.underline))
                        {
                        byteArrayBuilder.Append(e.SetStyles(PrintStyle.Bold));
                        }
                        else if (!(b) && !(u) && contentObject.underline && !(contentObject.bold))
                        {
                        byteArrayBuilder.Append(e.SetStyles(PrintStyle.Underline));
                        }
                        else
                        {
                        byteArrayBuilder.Append(e.SetStyles(PrintStyle.None));
                        }


                        if (!(br) && v)
                        {
                        byteArrayBuilder.Append(e.SetBarcodeHeightInDots(300));
                        byteArrayBuilder.Append(e.SetBarWidth(BarWidth.Thin));
                        byteArrayBuilder.Append(e.SetBarLabelPosition(BarLabelPrintPosition.None));
                        byteArrayBuilder.Append(e.PrintBarcode(BarcodeType.CODE128, contentObject.barcode.ToString()));
                        byteArrayBuilder.Append(e.PrintLine(""));
                        }

                        if (!(qr) && v && !(w))
                        {
                            if (contentObject.size.ToString().Equals("1"))
                            {
                             byteArrayBuilder.Append(e.PrintQRCode(contentObject.qrcode.ToString(),TwoDimensionCodeType.QRCODE_MODEL2,Size2DCode.NORMAL,CorrectionLevel2DCode.PERCENT_7));
                             byteArrayBuilder.Append(e.PrintLine(""));
                                   
                                }
                            else if (contentObject.size.ToString().Equals("2"))
                            {
                             byteArrayBuilder.Append(e.PrintQRCode(contentObject.qrcode.ToString(), TwoDimensionCodeType.QRCODE_MODEL2, Size2DCode.LARGE, CorrectionLevel2DCode.PERCENT_7));
                            byteArrayBuilder.Append(e.PrintLine(""));
                                   
                                }
                            else if (contentObject.size.ToString().Equals("0"))
                            {
                            byteArrayBuilder.Append(e.PrintQRCode(contentObject.qrcode.ToString(), TwoDimensionCodeType.QRCODE_MODEL2, Size2DCode.SMALL, CorrectionLevel2DCode.PERCENT_7));
                            byteArrayBuilder.Append(e.PrintLine(""));
                                   
                                }
                            else
                            {
                            byteArrayBuilder.Append(e.PrintQRCode(contentObject.qrcode.ToString(), TwoDimensionCodeType.QRCODE_MODEL2, Size2DCode.LARGE, CorrectionLevel2DCode.PERCENT_7));
                            byteArrayBuilder.Append(e.PrintLine(""));
                                    
                            }

                        }

                        if (!contentObject.logoBase64String.ToString().IsNullOrEmpty() && v)
                        {
                            //Bitmap codeBitmap = new Bitmap(base64ImageToBitmap(contentObject.logoBase64String.ToString()));
                            //Image image = (Image)codeBitmap;
                            //ImageConverter converter = new ImageConverter();
                            //byteArrayBuilder.Append(e.PrintImage((byte[])converter.ConvertTo(image, typeof(byte[])), true));
                            //e.PrintImage(File.ReadAllBytes("images/pd-logo-300.png"), true),
                            //printer.Image(image);

                            }

                        if (!(v) && !(f) && contentObject.fontType.ToString().Equals("A"))
                        {
                        //https://escpos.readthedocs.io/en/latest/font_cmds.html
                        byteArrayBuilder.Append(e.Print("\x1b\x50\x01"));
                        byteArrayBuilder.Append(e.PrintLine(contentObject.value.ToString()));   
                        }
                        if (!(v) && !(f) && !f && contentObject.fontType.ToString().Equals("B"))
                        {
                           byteArrayBuilder.Append(e.SetStyles(PrintStyle.FontB));
                           byteArrayBuilder.Append(e.Print("\x1b\x50\x01"));
                           byteArrayBuilder.Append(e.PrintLine(contentObject.value.ToString()));
                         }
                        if (!(v) && !(f) && contentObject.fontType.ToString().Equals("C"))
                        {
                        //byteArrayBuilder.Append(e.SetStyles(PrintStyle.FontB));
                        byteArrayBuilder.Append(e.Print("\x1b\x54\x01"));
                        byteArrayBuilder.Append(e.PrintLine(contentObject.value.ToString()));
                        }
                        if (!(v) && !(f) && contentObject.fontType.ToString().Equals("D"))
                        {
                        byteArrayBuilder.Append(e.SetStyles(PrintStyle.FontB));
                        byteArrayBuilder.Append(e.Print("\x1b\x55\x01"));
                        byteArrayBuilder.Append(e.PrintLine(contentObject.value.ToString()));
                        }
                        if (!(v) && !(f) && contentObject.fontType.ToString().Equals("E"))
                        {
                        byteArrayBuilder.Append(e.Print("\x1b\x55\x01"));
                        byteArrayBuilder.Append(e.PrintLine(contentObject.value.ToString()));
                        }

                        if (!contentObject.newLines.ToString().IsNullOrEmpty() && contentObject.newLines > 1)
                        {
                                for(int x = 0; x < contentObject.newLines-1; x++) {
                                   byteArrayBuilder.Append(e.PrintLine(""));
                                }
                                
                        }

                        if (!contentObject.separator.ToString().IsNullOrEmpty())
                        {
                        byteArrayBuilder.Append(e.SetStyles(PrintStyle.None));
                        byteArrayBuilder.Append(e.CenterAlign());
                        //this one for 80mm paper role
                        string sep = "------------------------------------------------";
                        string newSep = "";
                        foreach(char ch in sep)
                        {
                            newSep = newSep + (contentObject.separator.ToString().ToCharArray()[0]);
                        }
                        byteArrayBuilder.Append(e.PrintLine(newSep));
                         
                        }
                    byteArrayBuilder.Append(e.SetStyles(PrintStyle.None));

                            i++;
                    }
                    i = 1;
                }

            byteArrayBuilder.Append(e.LeftAlign());
            byteArrayBuilder.Append(e.PrintLine(""));
            byteArrayBuilder.Append(e.PrintLine(""));
            byteArrayBuilder.Append(e.PrintLine(""));
            byteArrayBuilder.Append(e.PrintLine(""));
           
            if (!recieptJsonClass.autoCut.ToString().IsNullOrEmpty() && recieptJsonClass.autoCut)
            {
                byteArrayBuilder.Append(e.FullCut());
            }
            
           
            try
            {
                printerEpson.WriteAsync(byteArrayBuilder.ToArray());
            }
            catch(Exception ex)
            {
                throw ex;
            }
           
            byteArrayBuilder.Clear();
        }

        private void printByUSB(RecieptJsonClass recieptJsonClass)
    {

            // sample code pages
            //https://learn.microsoft.com/en-us/dotnet/api/system.text.encoding?view=net-7.0
            Printer printer = new Printer(recieptJsonClass.printerName.ToString());
            // Printer printer = new Printer(recieptJsonClass.printerName.ToString(), "CP720");
            // printer.Append("الأم جميلة جدا.");

            if (!recieptJsonClass.openDrawer.ToString().IsNullOrEmpty() && recieptJsonClass.openDrawer)
            {
                printer.OpenDrawer();
            }

            if (!recieptJsonClass.topLogoBase64String.ToString().IsNullOrEmpty())
        {
           // printer.Append("-------------------------");
            Bitmap image = new Bitmap(base64ImageToBitmap(recieptJsonClass.topLogoBase64String.ToString()));
           // Bitmap reSizedImage = new Bitmap(image, 100, 50);
            printer.AlignCenter();
                // printer.Image(reSizedImage);
                printer.Image(image);
            //    printer.Append("-------------------------");
                printer.NewLines(3);
        }

        int i = 1;
        if (recieptJsonClass.content.Count > 0)
        {
            foreach (var item in recieptJsonClass.content)
            {
                Content contentObject = JsonConvert.DeserializeObject<Content>(item.ToString());

                Boolean v = contentObject.value.ToString().IsNullOrEmpty();
                Boolean b = contentObject.bold.ToString().IsNullOrEmpty();
                Boolean u = contentObject.underline.ToString().IsNullOrEmpty();
                Boolean f = contentObject.fontType.ToString().IsNullOrEmpty();
                Boolean w = contentObject.size.ToString().IsNullOrEmpty();
                Boolean br = contentObject.barcode.ToString().IsNullOrEmpty();
                Boolean qr = contentObject.qrcode.ToString().IsNullOrEmpty();


                if (!contentObject.align.ToString().IsNullOrEmpty())
                {
                    if (contentObject.align == "left" || contentObject.align == "right" || contentObject.align == "center")
                    {

                        if (contentObject.align == "left")
                        {
                            printer.AlignLeft();
                        }
                        else if (contentObject.align == "right")
                        {
                            printer.AlignRight();

                        }
                        else if (contentObject.align == "center")
                        {
                            printer.AlignCenter();
                        }
                        else
                        {
                            printer.AlignLeft();
                        }
                    }
                }
                else
                {
                    printer.AlignLeft();
                }

                if (!w && contentObject.size.ToString().Equals("1"))
                {
                    printer.NormalWidth();
                }
                else if (!w && contentObject.size.ToString().Equals("2"))
                {
                    printer.DoubleWidth2();
                }
                else if (!w && contentObject.size.ToString().Equals("3"))
                {
                    printer.DoubleWidth3();
                }
                else
                {
                    printer.NormalWidth();
                }


                if (!(b) && !(u) && contentObject.bold && contentObject.underline)
                {
                    printer.BoldMode(PrinterModeState.On);
                    printer.UnderlineMode(PrinterModeState.On);
                }
                else if (!(b) && !(u) && contentObject.bold && !(contentObject.underline))
                {
                    printer.BoldMode(PrinterModeState.On);
                }
                else if (!(b) && !(u) && contentObject.underline && !(contentObject.bold))
                {
                    printer.UnderlineMode(PrinterModeState.On);
                }
                else
                {
                    printer.BoldMode(PrinterModeState.Off);
                    printer.UnderlineMode(PrinterModeState.Off);
                }


                if (!(br) && v)
                {
                    printer.Code128(contentObject.barcode.ToString());
                
                }

                if (!(qr) && v && !(w))
                {
                    if (contentObject.size.ToString().Equals("1"))
                    {
                        printer.QrCode(contentObject.qrcode.ToString(), QrCodeSize.Size1);
                   
                    }
                    else if (contentObject.size.ToString().Equals("2"))
                    {
                        printer.QrCode(contentObject.qrcode.ToString(), QrCodeSize.Size2);
                      
                    }
                    else if (contentObject.size.ToString().Equals("0"))
                    {
                        printer.QrCode(contentObject.qrcode.ToString(), QrCodeSize.Size0);
                       
                    }
                    else
                    {
                        printer.QrCode(contentObject.qrcode.ToString(), QrCodeSize.Size1);
                      
                    }

                }

                if (!contentObject.logoBase64String.ToString().IsNullOrEmpty() && v)
                {
                    Bitmap image = new Bitmap(base64ImageToBitmap(contentObject.logoBase64String.ToString()));
                    printer.Image(image);

                }

                if (!(v) && !(f) && contentObject.fontType.ToString().Equals("A"))
                {
                    printer.Font(contentObject.value.ToString(), Fonts.FontA);
                }
                if (!(v) && !(f) && !f && contentObject.fontType.ToString().Equals("B"))
                {
                    printer.Font(contentObject.value.ToString(), Fonts.FontB);
                }
                if (!(v) && !(f) && contentObject.fontType.ToString().Equals("C"))
                {
                    printer.Font(contentObject.value.ToString(), Fonts.FontC);
                }
                if (!(v) && !(f) && contentObject.fontType.ToString().Equals("D"))
                {
                    printer.Font(contentObject.value.ToString(), Fonts.FontD);
                }
                if (!(v) && !(f) && contentObject.fontType.ToString().Equals("E"))
                {
                    printer.Font(contentObject.value.ToString(), Fonts.FontE);
                }

                if (!contentObject.newLines.ToString().IsNullOrEmpty() && contentObject.newLines > 0)
                {
                    printer.NewLines(contentObject.newLines);
                }

                if (!contentObject.separator.ToString().IsNullOrEmpty())
                {
                    printer.Separator(contentObject.separator.ToCharArray()[0]);
                }


                //printer modes off
                printer.NormalWidth();
                printer.BoldMode(PrinterModeState.Off);
                printer.UnderlineMode(PrinterModeState.Off);

                i++;
            }
            i = 1;
        }
        printer.AlignLeft();
        printer.NewLine();
        if (!recieptJsonClass.autoCut.ToString().IsNullOrEmpty() && recieptJsonClass.autoCut)
        {
            printer.FullPaperCut();
        }
            try
            {
              
                printer.PrintDocument();
            }
            catch(Exception ex)
            {
                throw ex;
            }
       
    }
    protected override void OnMessage(MessageEventArgs e)
    {

        try
        {
            if (e.Data != null)
            {

                var recieptJsonClassObj = JsonConvert.DeserializeObject<RecieptJsonClass>(e.Data);
                if (!recieptJsonClassObj.printerName.ToString().IsNullOrEmpty())
                {
                        if (recieptJsonClassObj.printerName.ToString().Contains("IP="))
                        {
                            printByIPAddress(recieptJsonClassObj);
                        }

                        else if (recieptJsonClassObj.printerName.ToString().Contains("BLUETOOTH="))
                        {
                            printByBluetooth(recieptJsonClassObj);
                        }

                        else if (!recieptJsonClassObj.printerName.ToString().Contains("USB="))
                        {
                            printByUSB(recieptJsonClassObj);
                        }

                        else if (!recieptJsonClassObj.printerName.ToString().Contains("IP=")
                            && !recieptJsonClassObj.printerName.ToString().Contains("BLUETOOTH=")
                            )
                        {
                            printByUSB(recieptJsonClassObj);
                        }

                    }

            }
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex);
        }
        //Broadcast/send to all the data to other end points "ws://127.0.0.1:7890/POSMSG You Send Data :"
        Sessions.Broadcast(e.Data);
    }
}

internal static class Program
    {
        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {

            //background-startup time auto run
            //RegistryKey rkApp = Registry.LocalMachine.OpenSubKey("SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run", true);
            //rkApp.SetValue("ESCPOSThermalPrinterUSBSupport", Assembly.GetExecutingAssembly().Location);
            //localhost:7890 == ip => 127.0.0.1:7890  Web socket API end point define
            WebSocketServer wssv = new WebSocketServer("ws://127.0.0.1:7890");
            wssv.AddWebSocketService<POSMSGES>("/POSMSGES");
            wssv.AddWebSocketService<AccessListOfPrinters>("/PRINTERS");
            wssv.AddWebSocketService<AccessListOfBluetoothPrinters>("/BLUETOOTHDEVICES");

            wssv.Start();
            // wssv.Stop();

            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new Form1());


           
        }
    }
}
